language: java
branches:
  only:
  - master
  - /^releases[/].+$/
addons:
  sonarcloud:
    organization: "coderanch-corral"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar